# Judge0 Configuration

# Telemetry
JUDGE0_TELEMETRY_ENABLE=false

# Server
RESTART_MAX_TRIES=10
MAINTENANCE_MODE=false
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=true
ENABLE_COMMAND_LINE_ARGUMENTS=true
ENABLE_BATCHED_SUBMISSIONS=true
MAX_SUBMISSION_BATCH_SIZE=20
ENABLE_CALLBACKS=false
ENABLE_ADDITIONAL_FILES=false
SUBMISSION_CACHE_DURATION=1

# Workers
INTERVAL=0.1
COUNT=2
MAX_QUEUE_SIZE=100

# Redis
REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0_redis_pass

# PostgreSQL
POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_db_pass

# Submission Limits
CPU_TIME_LIMIT=5
MAX_CPU_TIME_LIMIT=15
WALL_TIME_LIMIT=20
MAX_WALL_TIME_LIMIT=30
MEMORY_LIMIT=128000
MAX_MEMORY_LIMIT=512000
STACK_LIMIT=64000
MAX_STACK_LIMIT=128000
MAX_PROCESSES_AND_OR_THREADS=60
MAX_FILE_SIZE=1024
NUMBER_OF_RUNS=1
REDIRECT_STDERR_TO_STDOUT=true
ENABLE_NETWORK=false
ALLOW_ENABLE_NETWORK=false
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true

# Rails
RAILS_ENV=production
SECRET_KEY_BASE=skillnest_judge0_secret_key_base_do_not_use_in_production
